//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace RoyalCode.SmartProblems.Descriptions.Documentation
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class R
    {
        private static global::System.Resources.ResourceManager? resourceMan;
        private static global::System.Globalization.CultureInfo? resourceCulture;

        internal R()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                resourceMan ??= new global::System.Resources.ResourceManager("RoyalCode.SmartProblems.Descriptions.Documentation.R", typeof(R).Assembly);
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string DocumentedTypesLabel => ResourceManager.GetString("DocumentedTypesLabel", resourceCulture)!;
        internal static string IntroText => ResourceManager.GetString("IntroText", resourceCulture)!;
        internal static string IntroTitle => ResourceManager.GetString("IntroTitle", resourceCulture)!;
        internal static string NavigationDescription => ResourceManager.GetString("NavigationDescription", resourceCulture)!;
        internal static string NavigationTitle => ResourceManager.GetString("NavigationTitle", resourceCulture)!;
        internal static string PageDescription => ResourceManager.GetString("PageDescription", resourceCulture)!;
        internal static string PageTitle => ResourceManager.GetString("PageTitle", resourceCulture)!;
        internal static string PageUriLabel => ResourceManager.GetString("PageUriLabel", resourceCulture)!;
        internal static string ProblemTypeSourceExplicit => ResourceManager.GetString("ProblemTypeSourceExplicit", resourceCulture)!;
        internal static string ProblemTypeSourceGenerated => ResourceManager.GetString("ProblemTypeSourceGenerated", resourceCulture)!;
        internal static string RfcLabel => ResourceManager.GetString("RfcLabel", resourceCulture)!;
        internal static string SourceLabel => ResourceManager.GetString("SourceLabel", resourceCulture)!;
        internal static string StatusLabel => ResourceManager.GetString("StatusLabel", resourceCulture)!;
        internal static string StatusUnknown => ResourceManager.GetString("StatusUnknown", resourceCulture)!;
        internal static string TypeIdLabel => ResourceManager.GetString("TypeIdLabel", resourceCulture)!;
        internal static string TypeUriLabel => ResourceManager.GetString("TypeUriLabel", resourceCulture)!;
    }
}
